### ISSUE TITLE
Make sentry-airflow installable

### ISSUE THREAD

**Issue by n8sty** [getsentry/sentry_airflow#13]
Instead of having to clone or copy this repo's contents into an instance of Airflow, I'd like to be able to `pip install sentry-airflow` and have it automatically get included as part of my environment. I'm happy to work on this and already have it nearly finished, but am interested in whether this would be a welcome addition or if I should maintain my own fork? If you are interested in this contribution, let me know if you have anything you'd want me to include and I'll do my best to add it.

**Comment by mikeclarke** [comment]
I think initially we were trying to fit the model used by Astronomer and other airflow plugins, but we could certainly make this installable directly via `pip` as well. I thought for it to be picked up as a plugin it needed to have a reference within the plugins directory to load this - but maybe this library can still be useful without having it available via `plugins/`?

**Comment by n8sty** [comment]
I *believe* that the plugin gets automatically loaded if it's configured to use the entrypoint mechanism allowed for by `setuptools`. I've done something like the following (in `pyproject.toml`):

```
[tool.poetry.plugins."airflow.plugins"]
"airflow-sentry" = "sentry_airflow:SentryPlugin"
```

which gets the plugin loaded automatically after it's been installed by `pip install sentry-airflow` without having to copy anything into the plugins directory. I referenced https://airflow.apache.org/plugins.html#plugins-as-python-packages when I did the above. Want me to throw up a PR in the next few days so this can be seen in action?

**Comment by nathan-heskia** [comment]
We've decided to follow a pattern from `airflow-plugins` (ex. [mysql_plugin](https://github.com/airflow-plugins/mysql_plugin), [google_analytics_plugin](https://github.com/airflow-plugins/google_analytics_plugin) which uses a top-level `__init__.py` file. If you'd like to install the plugin as a package, it makes sense to maintain your own fork.
