### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by rrbarbosa** [getsentry/sentry_airflow#14]
Although the plugin seems to work fine, I had problems installing it following the instructions in the `README`, i.e., cloning the repo into `plugins`.

I got, and "fixed", three errors:

- `ERROR - signalling support is unavailable because the blinker library is not installed.`

Solution: manually install `blinker`.

- `ERROR - No module named 'freezegun'`

Solution: remove `/tests` folder or manually install `freezegun`  

-  `ERROR - No module named 'sentry_plugin'`

Solution: Looking at [astronomer's plugins guide](https://www.astronomer.io/guides/airflow-importing-custom-hooks-operators/), I've noticed the `__init__.py` files are not required, so I removed them. 

As no one else had similar problems, I'm probably missing something obvious. Is there a step missing in the `README`?

**Comment by diogosantos** [comment]
I am having the same issues you pointed out. With your instructions, I was able to remove all the errors on Airflow, but I don't get any events on Sentry. So, no sure what's going on right now.

**Comment by mikeclarke** [comment]
Interesting - we didn't run into this when we added the plugin to composer, but let me confirm with a fresh install. Which airflow version are you running?

**Comment by tiopi** [comment]
It looks like the `blinker` library needs to be added to the installation instructions. The tests should not be imported by airflow unless all of the package is placed under the `plugins/` folder. Removing the `__init__.py` files might cause airflow to lose track of sentry.

**Comment by rrbarbosa** [comment]
@mikeclarke i'm using version 1.10.3

@tiopi agreed on `blinker`, I would also add instructions on which folders/files not to copy, like the `tests` folder. 

What do you mean by "might cause airflow to lose track of sentry"? I've managed to trigger an issue in sentry with the setup described above. Why would airflow lose track of sentry?

**Comment by tiopi** [comment]
> What do you mean by "might cause airflow to lose track of sentry"? I've managed to trigger an issue in sentry with the setup described above. Why would airflow lose track of sentry?

Since `sentry_plugin` should be under `plugins/`, I ran into issues with `sentry_hook.py` not being found and therefore no exceptions going to Sentry. Are you running Airflow locally?

**Comment by rrbarbosa** [comment]
I'm running it on docker. I've prepared a small example showing the `__init__.py`, with minimal changes from the Puckel's docker-airflows. You can find it here:

https://github.com/rrbarbosa/docker-airflow/tree/feat/sentry

All you need to do is to fill `.env` with a valid run `docker-compose build` then `docker-compose up` to reproduce the issue.

**Comment by diogosantos** [comment]
> > What do you mean by "might cause airflow to lose track of sentry"? I've managed to trigger an issue in sentry with the setup described above. Why would airflow lose track of sentry?
> 
> Since `sentry_plugin` should be under `plugins/`, I ran into issues with `sentry_hook.py` not being found and therefore no exceptions going to Sentry. Are you running Airflow locally?

This is the same behaviour I had here. Airflow didn't trigger any events on Sentry at all. Just ignored it after removing the __init__ files.

**Comment by nathan-heskia** [comment]
We've changed the directory structure. You should be able to add this repository to your `plugins` directory, run `pip install -r requirements.txt` in your Airflow environment and have Airflow register the plugin on startup. To successfully import/run the tests, `freezegun` should be installed, but it is not required to report errors to Sentry.
